# Generated by Django 6.0.6 on 2026-06-20 17:21

import portal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestWifiSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('room_number', models.CharField(max_length=64)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField()),
                ('marketing_consent', models.BooleanField(default=False)),
                ('marketing_consent_at', models.DateTimeField(blank=True, null=True)),
                ('client_mac', models.CharField(blank=True, max_length=64)),
                ('ap_mac', models.CharField(blank=True, max_length=64, null=True)),
                ('gateway_mac', models.CharField(blank=True, max_length=64, null=True)),
                ('vlan_id', models.CharField(blank=True, max_length=32, null=True)),
                ('ssid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_id', models.CharField(blank=True, max_length=32, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('omada_timestamp', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('auth_duration_minutes', models.PositiveIntegerField(default=portal.models.default_auth_duration_minutes)),
                ('omada_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
