# Generated by Django 6.0.6 on 2026-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestwifisession',
            name='google_sheets_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guestwifisession',
            name='google_sheets_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestwifisession',
            name='google_sheets_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestwifisession',
            name='google_sheets_status',
            field=models.CharField(choices=[('not_configured', 'Not configured'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_configured', max_length=20),
        ),
    ]
