# Generated by Django 6.0.6 on 2026-06-21 04:23

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_guestwifisession_google_sheets_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('brand_name', models.CharField(default=portal.models.default_portal_brand_name, max_length=255)),
                ('tagline', models.CharField(default=portal.models.default_portal_tagline, max_length=255)),
                ('logo_url', models.CharField(blank=True, default=portal.models.default_portal_logo_url, help_text='Optional local static path or absolute URL.', max_length=2048)),
                ('background_url', models.CharField(blank=True, default=portal.models.default_portal_background_url, help_text='Optional local static path or absolute URL.', max_length=2048)),
                ('primary_color', models.CharField(default=portal.models.default_portal_primary_color, help_text='CSS colour used for primary buttons and brand accents.', max_length=32)),
                ('support_text', models.TextField(blank=True, default=portal.models.default_portal_support_text)),
                ('success_message', models.TextField(default=portal.models.default_portal_success_message)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portal customization',
                'verbose_name_plural': 'portal customization',
            },
        ),
    ]
