# Generated by Codex on 2026-06-23

import re

import django.core.validators
from django.db import migrations, models

import portal.models

DEFAULTS = {
    "brand_name": "Kingfield Hotel",
    "tagline": "Guest Wi-Fi",
    "logo_url": "",
    "background_url": "",
    "primary_color": "#0b6b61",
    "support_text": "Need help? Please contact reception.",
    "success_message": "You are connected. You can now continue browsing.",
}
REQUIRED_FIELDS = ("brand_name", "tagline", "primary_color", "success_message")
HEX_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


def seed_portal_customization(apps, _schema_editor):
    PortalCustomization = apps.get_model("portal", "PortalCustomization")
    customization = PortalCustomization.objects.first()
    if customization is None:
        PortalCustomization.objects.create(**DEFAULTS)
        return

    update_fields = []
    for field in REQUIRED_FIELDS:
        value = (getattr(customization, field) or "").strip()
        if field == "primary_color" and not HEX_COLOR_RE.fullmatch(value):
            value = DEFAULTS[field]
        elif not value:
            value = DEFAULTS[field]

        if getattr(customization, field) != value:
            setattr(customization, field, value)
            update_fields.append(field)

    if customization.singleton_key != 1:
        customization.singleton_key = 1
        update_fields.append("singleton_key")

    if update_fields:
        customization.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_portalcustomization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalcustomization",
            name="primary_color",
            field=models.CharField(
                default=portal.models.default_portal_primary_color,
                help_text="CSS colour used for primary buttons and brand accents.",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex colour like #0b6b61.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.RunPython(
            seed_portal_customization,
            migrations.RunPython.noop,
        ),
    ]
